config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'index' => 'home#index'

  get 'admin' => 'admin#index'
  get 'admin/auth' => 'admin#auth'
  get 'admin/auth/callback' => 'admin#callback'
  get 'admin/get_playlists' => 'admin#get_playlists'
  get 'admin/get_tracks' => 'admin#get_tracks'
  patch 'admin/select_playlist' => 'admin#select_playlist'
  delete 'admin/logout' => 'admin#logout'

end

app/views/admin/_playlist_select.html.erb
<div class="playlist-select">
  <%= form_for @user, url: admin_select_playlist_path do |f| %>
    <div class="radio">
      <label>
        <%= f.radio_button(:selected_playlist_id, "", class: "radio") %>
        Use your "My Music" library
        <%= content_tag :small, "[private]", class: "text-muted" %>
      </label>
    </div>
    <% unless @playlists.count==0 %>
      <div><strong>Or use one of your playlists:</strong></div>
      <% @playlists.each do |pl| %>
        <div class="radio">
          <label>
            <%= f.radio_button(:selected_playlist_id, pl[:playlist_id], class: "radio") %>
            <%= pl[:name] %>
            <%= content_tag :small, "[private]", class: "text-muted" unless pl.public %>
          </label>
        </div>
      <% end %>
    <% else %>
      <div>You have no playlists.</div>
    <% end %>

    <%= f.submit "Populate tracks", class: "btn btn-primary", data: {disable_with: "Populating..."} %>
    <%= link_to 'Refresh playlists', admin_get_playlists_path, {class: "btn btn-default", role: "button", data: {disable_with: "Refreshing..."}} %>
    <%= link_to 'Close', root_path %>
  <% end %>
</div>

app/views/admin/index.html.erb
<div class="admin-outer">
  <div class="container admin">
    <% if User.count==0 %>
      <div class="user">
        You are not signed in.
        <%= link_to 'Sign in with Spotify', '/admin/auth', {class: "btn btn-info", role: "button"} %>
      </div>
    <% else %>
      <div class="user">
        Currently signed in as <strong><%= content_tag :a, @user.user_id, href: @user.url, class: "user-id" %></strong>.
        <%= link_to 'Sign out', admin_logout_path, {class: "btn btn-danger btn-xs", role: "button", method: :delete, data: {confirm: "Are you sure you want to sign out?"}} %>
      </div>
      <%= render 'playlist_select' %>
    <% end %>
  </div>
</div>

<%= render 'home/album_listings' %>