config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'index' => 'home#index'

  get 'admin' => 'admin#index'
  get 'admin/auth' => 'admin#auth'
  get 'admin/auth/callback' => 'admin#callback'
  get 'admin/get_playlists' => 'admin#get_playlists'
  get 'admin/get_tracks' => 'admin#get_tracks'
  patch 'admin/select_playlist' => 'admin#select_playlist'
  delete 'admin/logout' => 'admin#logout'

end

app/views/layouts/_alerts.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>"><span class="glyphicon glyphicon-<%= (name=="danger" ? "exclamation" : "info") %>-sign" aria-hidden="true"></span> <%= msg %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="footer-items">
    <% if params[:controller]!="admin" %>
      <%= link_to "Admin", admin_path, class: "text-muted", title: "Admin panel (requires admin)" %>
      <span class="text-muted">:</span>
      <%= link_to admin_get_tracks_path(quick: true), class: "text-muted", title: "Refresh tracks (requires admin)" do %>
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
      <% end %>
    <% elsif User.count!=0 %>
      <%= link_to "Home", root_path, class: "text-muted", title: "Return to home" %>
    <% end %>

    <% unless ENV['source_url'] == nil or ENV['source_url'] == "" %>
      <% if User.count!=0 %>
        <div class="text-muted">&#8226;</div>
      <% end %>
      <%= content_tag :a, class: "text-muted", href: ENV['source_url'], target: "_blank", title: "View the source code" do %>
        Source 
        <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
      <% end %>
    <% end %>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaylistPresent</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/alerts' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>